In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
df=pd.read_csv('../Data/Clean/beer_reviews_all_columns.csv')

In [4]:
df.columns

Index(['review_overall', 'review_aroma', 'review_appearance', 'beer_style',
       'review_palate', 'review_taste', 'year'],
      dtype='object')

In [10]:
df.groupby(df['beer_style'])[['review_overall', 'review_aroma', 'review_appearance', 'review_palate', 'review_taste']].mean().round(2)

,review_overall,review_aroma,review_appearance,review_palate,review_taste
beer_style,,,,,
1,3.77,3.66,3.84,3.69,3.71
2,3.57,3.27,3.59,3.44,3.43
3,3.88,3.98,4.01,3.95,3.99
4,3.92,3.91,4.10,3.89,3.94
5,3.84,3.77,3.88,3.75,3.85
6,3.60,3.33,3.57,3.58,3.47
7,3.90,3.86,3.96,3.80,3.91
8,3.45,3.14,3.38,3.36,3.28
9,4.04,4.14,4.14,4.07,4.16
10,3.96,3.96,4.01,3.92,3.96
11,2.98,2.54,2.87,2.82,2.74
12,3.84,3.69,3.82,3.72,3.73
13,3.82,3.85,3.93,3.71,3.83
14,3.77,3.91,3.85,3.86,3.89
15,3.63,3.48,3.58,3.54,3.51
16,3.94,3.92,3.99,3.89,4.00
18,3.89,3.85,3.95,3.84,3.90
19,3.99,4.00,3.96,3.95,4.05
20,3.88,3.90,3.95,3.88,3.94
21,4.02,4.05,4.01,3.97,4.06
22,3.81,3.75,3.88,3.76,3.76
23,4.07,4.09,4.06,4.07,4.16
24,3.94,3.92,3.99,3.88,3.91
25,3.91,3.90,3.94,3.90,3.94
26,3.72,3.63,3.67,3.62,3.63
30,3.91,4.00,3.88,3.94,4.01
31,3.85,3.57,3.82,3.76,3.75
34,3.94,3.74,3.89,3.92,3.88
35,3.76,3.52,3.75,3.61,3.61
36,3.76,3.59,3.77,3.60,3.69
37,3.88,3.82,3.91,3.76,3.87
38,3.68,3.54,3.79,3.66,3.62
39,3.79,3.53,3.73,3.58,3.63
40,3.85,3.79,3.93,3.75,3.83
41,3.93,4.02,3.91,3.94,4.06
42,3.65,3.44,3.70,3.56,3.52
43,3.89,3.83,3.93,3.80,3.89
45,3.84,3.79,3.87,3.80,3.82
46,3.45,3.55,3.55,3.44,3.44
47,3.78,3.62,3.81,3.70,3.72
48,3.60,3.44,3.69,3.52,3.55
49,3.84,3.84,3.87,3.84,3.91
50,3.72,3.48,3.73,3.58,3.61
51,3.82,3.75,3.83,3.72,3.77
52,3.90,3.75,3.81,3.77,3.80
53,3.82,3.50,3.66,3.68,3.68
54,3.76,3.44,3.63,3.65,3.58
55,3.80,3.60,3.80,3.75,3.73
56,3.72,3.42,3.63,3.60,3.56
57,3.78,3.62,3.86,3.66,3.73
58,4.00,4.01,3.99,3.96,4.02
59,3.52,3.59,3.63,3.54,3.56
62,3.73,3.54,3.98,3.58,3.59
63,3.58,3.38,3.73,3.50,3.48
65,3.67,3.79,3.72,3.62,3.67
67,3.86,3.85,3.85,3.85,3.93
68,3.74,3.59,3.78,3.65,3.69
70,3.74,3.81,3.81,3.69,3.77
71,3.73,3.43,3.75,3.60,3.60
72,3.73,3.50,3.73,3.64,3.64

In [11]:
df_beers_data=pd.read_csv('../Data/Clean/standard_beer_types_features_clean.csv')

In [12]:
df_beers_data[df_beers_data['style_id']==10]

                beer_style color bitterness  alcohol  style_id
9  american india pale ale  Gold       High  Regular        10

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503104 entries, 0 to 503103
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   review_overall     503104 non-null  float64
 1   review_aroma       503104 non-null  float64
 2   review_appearance  503104 non-null  float64
 3   style_id           503104 non-null  int64
 4   review_palate      503104 non-null  float64
 5   review_taste       503104 non-null  float64
 6   year               503104 non-null  int64
dtypes: float64(5), int64(2)
memory usage: 26.9 MB

In [15]:
df_beers_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   beer_style  72 non-null     object
 1   color       72 non-null     object
 2   bitterness  72 non-null     object
 3   alcohol     72 non-null     object
 4   style_id    72 non-null     int64
dtypes: int64(1), object(4)
memory usage: 2.9+ KB